version: '3.4'

networks:
  survey-api-dev:
    driver: bridge

services:
  survey.api:
    container_name: survey.api
    image: ${DOCKER_REGISTRY-}surveyapi
    build:
      context: .
      dockerfile: Survey.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - survey-api-dev
    depends_on:
      - survey.database

  survey.database:
    container_name: survey.database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: survey_db
    ports:
      - "5432:5432"
    networks:
      - survey-api-dev
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: